version: '3.3'

services:
  app:
    build: .
    command: gunicorn tga.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    expose:
      - 8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
  bot:
    build: .
    command: python manage.py bot
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
volumes:
  media_volume:
  static_volume: